#!/usr/bin/env python3
# ABOUTME: Generates the skills catalog and plugin list sections for README.md
# ABOUTME: Reads frontmatter descriptions and outputs markdown lists, general skills first then an Internal section

import json
import re
import subprocess
from pathlib import Path
from skill_sources import read_index_file, tracked_skill_files

from typing import List, Tuple, Optional

REPO_ROOT = Path(__file__).parent.parent
README_PATH = REPO_ROOT / "README.md"
SKILLS_DIR = REPO_ROOT / "skills"
AGENTS_DIR = REPO_ROOT / "agents"

START_MARKER = "<!-- CATALOG:START -->"
END_MARKER = "<!-- CATALOG:END -->"
PLUGINS_START_MARKER = "<!-- PLUGINS:START -->"
PLUGINS_END_MARKER = "<!-- PLUGINS:END -->"


def extract_frontmatter_field(content: str, field: str) -> Optional[str]:
    """Extract a field value from YAML frontmatter."""
    frontmatter_match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not frontmatter_match:
        return None

    frontmatter = frontmatter_match.group(1)

    # Handle both quoted and unquoted values; allow indented keys (e.g. metadata.internal)
    pattern = rf'^\s*{field}:\s*["\']?(.*?)["\']?\s*$'
    match = re.search(pattern, frontmatter, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return None


def get_skills() -> List[Tuple[str, str, str, bool]]:
    """Get all skills as a flat sorted list of (name, path, description, is_internal)."""
    skills: List[Tuple[str, str, str, bool]] = []

    for skill_file in tracked_skill_files(REPO_ROOT):
        # Skip private directory (gitignored)
        if skill_file.parent.name == "private":
            continue

        content = read_index_file(REPO_ROOT, skill_file).decode()
        desc = extract_frontmatter_field(content, "description")
        if not desc:
            desc = "(no description)"

        internal = extract_frontmatter_field(content, "internal")
        is_internal = str(internal).lower() == "true"

        name = skill_file.parent.name
        path = skill_file.parent.relative_to(REPO_ROOT).as_posix() + "/"
        skills.append((name, path, desc, is_internal))

    skills.sort(key=lambda x: x[0])
    return skills


def get_agents() -> List[Tuple[str, str, str]]:
    """Subagent definitions as a sorted list of (name, path, description). README.md skipped."""
    agents: List[Tuple[str, str, str]] = []
    if not AGENTS_DIR.is_dir():
        return agents
    for f in AGENTS_DIR.glob("*.md"):
        if f.name == "README.md":
            continue
        content = f.read_text()
        name = extract_frontmatter_field(content, "name") or f.stem
        desc = extract_frontmatter_field(content, "description") or "(no description)"
        agents.append((name, f"agents/{f.name}", desc))
    agents.sort(key=lambda x: x[0])
    return agents


def generate_catalog() -> str:
    """Generate the full catalog markdown: general skills, an Internal section, then Agents."""
    skills = get_skills()
    general = [s for s in skills if not s[3]]
    internal = [s for s in skills if s[3]]

    lines = [
        "<!-- CATALOG:START -->",
        "",
        "_Auto-generated by `scripts/update-catalog.py`_",
        "",
        "### Skills",
        "",
    ]

    for name, path, desc, _ in general:
        lines.append(f"- [{name}]({path}) — {desc}")
    lines.append("")

    if internal:
        lines.append("### Internal")
        lines.append("")
        lines.append(
            "Personal workflows tied to my own setup (vault paths, tools, naming "
            "conventions). Installable, but expect to adapt `SKILL.md` to your own "
            "folders and conventions before they're useful."
        )
        lines.append("")
        for name, path, desc, _ in internal:
            lines.append(f"- [{name}]({path}) — {desc}")
        lines.append("")

    agents = get_agents()
    if agents:
        lines.append("### Agents")
        lines.append("")
        lines.append(
            "Claude Code subagents — copy the `*.md` into your own agents directory "
            "(not installed by `bunx skills`). See [`agents/`](agents/)."
        )
        lines.append("")
        for name, path, desc in agents:
            lines.append(f"- [{name}]({path}) — {desc}")
        lines.append("")

    lines.append("<!-- CATALOG:END -->")
    return "\n".join(lines)


def get_plugins() -> List[Tuple[str, str, str]]:
    """Plugins as a sorted list of (display name, path, description) from staged plugin-source.json files."""
    paths = subprocess.check_output(
        ["git", "ls-files", "-z", "--", "plugins/*/plugin-source.json"], cwd=REPO_ROOT
    ).decode().split("\0")
    plugins: List[Tuple[str, str, str]] = []
    for text in filter(None, paths):
        source = REPO_ROOT / text
        data = json.loads(read_index_file(REPO_ROOT, source))
        display = data.get("interface", {}).get("displayName") or data["name"]
        plugins.append((display, source.parent.relative_to(REPO_ROOT).as_posix() + "/", data["description"]))
    plugins.sort(key=lambda x: x[0].lower())
    return plugins


def generate_plugin_list() -> str:
    """Generate the plugin list markdown for the README's Plugins section."""
    lines = [PLUGINS_START_MARKER, ""]
    for display, path, desc in get_plugins():
        lines.append(f"- [{display}]({path}) — {desc}")
    lines.extend(["", PLUGINS_END_MARKER])
    return "\n".join(lines)


def replace_between(content: str, start: str, end: str, replacement: str) -> str:
    pattern = re.compile(rf"{re.escape(start)}.*?{re.escape(end)}", re.DOTALL)
    return pattern.sub(lambda _: replacement, content)


def update_readme():
    """Update the README with the generated skill catalog and plugin list."""
    readme_content = README_PATH.read_text()

    # Check for markers
    missing = [m for m in (START_MARKER, END_MARKER, PLUGINS_START_MARKER, PLUGINS_END_MARKER)
               if m not in readme_content]
    if missing:
        print("Error: README.md missing generated-section markers:")
        for marker in missing:
            print(f"  {marker}")
        return False

    new_content = replace_between(readme_content, START_MARKER, END_MARKER, generate_catalog())
    new_content = replace_between(new_content, PLUGINS_START_MARKER, PLUGINS_END_MARKER, generate_plugin_list())

    README_PATH.write_text(new_content)
    print(f"Updated {README_PATH}")
    return True


if __name__ == "__main__":
    update_readme()
