#!/usr/bin/env python3
# ABOUTME: Generates the skills catalog section for README.md
# ABOUTME: Reads frontmatter descriptions and outputs markdown lists, general skills first then an Internal section

import re
from pathlib import Path

from typing import List, Tuple, Optional

REPO_ROOT = Path(__file__).parent.parent
README_PATH = REPO_ROOT / "README.md"
SKILLS_DIR = REPO_ROOT / "skills"
AGENTS_DIR = REPO_ROOT / "agents"

START_MARKER = "<!-- CATALOG:START -->"
END_MARKER = "<!-- CATALOG:END -->"


def extract_frontmatter_field(content: str, field: str) -> Optional[str]:
    """Extract a field value from YAML frontmatter."""
    frontmatter_match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not frontmatter_match:
        return None

    frontmatter = frontmatter_match.group(1)

    # Handle both quoted and unquoted values; allow indented keys (e.g. metadata.internal)
    pattern = rf'^\s*{field}:\s*["\']?(.*?)["\']?\s*$'
    match = re.search(pattern, frontmatter, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return None


def get_skills() -> List[Tuple[str, str, str, bool]]:
    """Get all skills as a flat sorted list of (name, path, description, is_internal)."""
    skills: List[Tuple[str, str, str, bool]] = []

    for skill_file in SKILLS_DIR.glob("*/SKILL.md"):
        # Skip private directory (gitignored)
        if skill_file.parent.name == "private":
            continue

        content = skill_file.read_text()
        desc = extract_frontmatter_field(content, "description")
        if not desc:
            desc = "(no description)"

        internal = extract_frontmatter_field(content, "internal")
        is_internal = str(internal).lower() == "true"

        name = skill_file.parent.name
        path = f"skills/{name}/"
        skills.append((name, path, desc, is_internal))

    skills.sort(key=lambda x: x[0])
    return skills


def get_agents() -> List[Tuple[str, str, str]]:
    """Subagent definitions as a sorted list of (name, path, description). README.md skipped."""
    agents: List[Tuple[str, str, str]] = []
    if not AGENTS_DIR.is_dir():
        return agents
    for f in AGENTS_DIR.glob("*.md"):
        if f.name == "README.md":
            continue
        content = f.read_text()
        name = extract_frontmatter_field(content, "name") or f.stem
        desc = extract_frontmatter_field(content, "description") or "(no description)"
        agents.append((name, f"agents/{f.name}", desc))
    agents.sort(key=lambda x: x[0])
    return agents


def generate_catalog() -> str:
    """Generate the full catalog markdown: general skills, an Internal section, then Agents."""
    skills = get_skills()
    general = [s for s in skills if not s[3]]
    internal = [s for s in skills if s[3]]

    lines = [
        "<!-- CATALOG:START -->",
        "",
        "_Auto-generated by `scripts/update-catalog.py`_",
        "",
        "### Skills",
        "",
    ]

    for name, path, desc, _ in general:
        lines.append(f"- [{name}]({path}) — {desc}")
    lines.append("")

    if internal:
        lines.append("### Internal")
        lines.append("")
        lines.append(
            "Personal workflows tied to my own setup (vault paths, tools, naming "
            "conventions). Installable, but expect to adapt `SKILL.md` to your own "
            "folders and conventions before they're useful."
        )
        lines.append("")
        for name, path, desc, _ in internal:
            lines.append(f"- [{name}]({path}) — {desc}")
        lines.append("")

    agents = get_agents()
    if agents:
        lines.append("### Agents")
        lines.append("")
        lines.append(
            "Claude Code subagents — copy the `*.md` into your own agents directory "
            "(not installed by `bunx skills`). See [`agents/`](agents/)."
        )
        lines.append("")
        for name, path, desc in agents:
            lines.append(f"- [{name}]({path}) — {desc}")
        lines.append("")

    lines.append("<!-- CATALOG:END -->")
    return "\n".join(lines)


def update_readme():
    """Update the README with the generated catalog."""
    readme_content = README_PATH.read_text()

    # Check for markers
    if START_MARKER not in readme_content or END_MARKER not in readme_content:
        print("Error: README.md missing catalog markers.")
        print("Add these markers where you want the catalog:")
        print(f"  {START_MARKER}")
        print(f"  {END_MARKER}")
        return False

    # Replace content between markers
    pattern = re.compile(
        rf"{re.escape(START_MARKER)}.*?{re.escape(END_MARKER)}",
        re.DOTALL,
    )

    new_catalog = generate_catalog()
    new_content = pattern.sub(new_catalog, readme_content)

    README_PATH.write_text(new_content)
    print(f"Updated {README_PATH}")
    return True


if __name__ == "__main__":
    update_readme()
